# fly.toml app configuration file generated for rozkladnyk on 2025-03-20T15:55:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rozkladnyk'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
